import os
import pytorch_lightning as pl
from datetime import datetime
import matplotlib.pyplot as plt
from omegaconf import OmegaConf

class SSLExperimentReporter(pl.Callback):
    def __init__(self, cfg, output_dir):
        self.cfg = cfg
        self.output_dir = output_dir
        self.report_path = os.path.join(output_dir, "SSL_REPORT.md")
        
        # История метрик
        self.history = {
            "epoch": [],
            "train_ssl_loss": [],
            "val_ssl_loss": []
        }

    def on_train_epoch_end(self, trainer, pl_module):
        metrics = trainer.callback_metrics
        epoch = trainer.current_epoch
        
        def get_val(key):
            val = metrics.get(key, None)
            return val.item() if val is not None else None

        self.history["epoch"].append(epoch)
        self.history["train_ssl_loss"].append(get_val("train_ssl_loss"))
        self.history["val_ssl_loss"].append(get_val("val_ssl_loss"))

    def _plot_loss_curve(self):
        epochs = self.history["epoch"]
        if not epochs: return None

        train_loss = self.history["train_ssl_loss"]
        val_loss = self.history["val_ssl_loss"]

        plt.figure(figsize=(10, 6))
        
        # Рисуем Train
        # Фильтруем None, если вдруг какая-то эпоха пропущена
        valid_train = [(e, v) for e, v in zip(epochs, train_loss) if v is not None]
        if valid_train:
            plt.plot(*zip(*valid_train), label="Train Contrastive Loss", marker='o', color='blue')

        # Рисуем Val
        valid_val = [(e, v) for e, v in zip(epochs, val_loss) if v is not None]
        if valid_val:
            plt.plot(*zip(*valid_val), label="Val Contrastive Loss", marker='s', color='orange')

        plt.title(f"SSL Training Dynamics ({self.cfg.project_name})")
        plt.xlabel("Epoch")
        plt.ylabel("NT-Xent Loss")
        plt.legend()
        plt.grid(True, linestyle='--', alpha=0.7)
        
        plot_path = os.path.join(self.output_dir, "ssl_loss_curve.png")
        plt.savefig(plot_path, dpi=100)
        plt.close()
        
        return "ssl_loss_curve.png"

    def on_train_end(self, trainer, pl_module):
        # 1. Рисуем график
        plot_img = self._plot_loss_curve()
        
        # 2. Получаем финальные значения
        def get_last_valid(lst):
            valid = [x for x in lst if x is not None]
            return valid[-1] if valid else "N/A"

        final_train = get_last_valid(self.history["train_ssl_loss"])
        final_val = get_last_valid(self.history["val_ssl_loss"])

        # Безопасное форматирование
        def fmt(val):
            return f"{val:.4f}" if isinstance(val, (int, float)) else str(val)

        # 3. Конфиг в YAML
        config_yaml = OmegaConf.to_yaml(self.cfg)
        
        # 4. Формируем отчет
        md_content = f"""# 🧠 Отчет SSL Pre-training: {self.cfg.project_name}

**ID:** `{os.path.basename(self.output_dir)}`  
**Дата:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}  
**Модель:** `{self.cfg.model.name}`  
**Аугментации:** `RandomCrop`, `Time/Freq Mask`, `Gaussian Noise`

## 1. Результаты (Pre-training)

| Метрика | Значение (Final) | Описание |
| :--- | :--- | :--- |
| **Train Loss** | **{fmt(final_train)}** | Насколько хорошо модель сближает аугментации (обучение) |
| **Val Loss** | **{fmt(final_val)}** | Проверка на отложенных данных (если есть) |

*Примечание: В SSL низкий Loss означает, что модель научилась вытягивать инвариантные признаки (устойчивые к шуму и обрезке).*

## 2. Динамика обучения
![Loss Curve]({plot_img})

## 3. Полная конфигурация
<details>
<summary>🔽 Развернуть конфиг (YAML)</summary>

```yaml
{config_yaml}
</details>
Generated by SSLExperimentReporter
"""
        with open(self.report_path, "w", encoding="utf-8") as f:
            f.write(md_content)
            print(f"\n📝 SSL Report saved to: {self.report_path}")
            print(f"📈 Plot saved as: {plot_img}")