import os
import pytorch_lightning as pl
from datetime import datetime
import matplotlib.pyplot as plt
from omegaconf import OmegaConf

class SSLExperimentReporter(pl.Callback):
    def __init__(self, cfg, output_dir):
        self.cfg = cfg
        self.output_dir = output_dir
        self.report_path = os.path.join(output_dir, "SSL_REPORT.md")
        
        # Определяем режим и ключи метрик
        self.ssl_mode = cfg.get("ssl_mode", "contrastive") # contrastive / denoising / reconstruction
        self.train_key = f"train_{self.ssl_mode}_loss"
        self.val_key = f"val_{self.ssl_mode}_loss"
        
        # История метрик
        self.history = {
            "epoch": [],
            "train_loss": [],
            "val_loss": []
        }

    def on_train_epoch_end(self, trainer, pl_module):
        metrics = trainer.callback_metrics
        epoch = trainer.current_epoch
        
        def get_val(key):
            val = metrics.get(key, None)
            return val.item() if val is not None else None

        self.history["epoch"].append(epoch)
        # Используем динамические ключи
        self.history["train_loss"].append(get_val(self.train_key))
        self.history["val_loss"].append(get_val(self.val_key))

    def _plot_loss_curve(self):
        epochs = self.history["epoch"]
        if not epochs: return None

        train_loss = self.history["train_loss"]
        val_loss = self.history["val_loss"]

        plt.figure(figsize=(10, 6))
        
        valid_train = [(e, v) for e, v in zip(epochs, train_loss) if v is not None]
        if valid_train:
            plt.plot(*zip(*valid_train), label=f"Train {self.ssl_mode.capitalize()} Loss", marker='o', color='blue')

        valid_val = [(e, v) for e, v in zip(epochs, val_loss) if v is not None]
        if valid_val:
            plt.plot(*zip(*valid_val), label=f"Val {self.ssl_mode.capitalize()} Loss", marker='s', color='orange')

        plt.title(f"SSL Dynamics ({self.cfg.project_name})")
        plt.xlabel("Epoch")
        
        # Подпись оси Y зависит от лосса
        ylabel = "MSE Loss" if self.ssl_mode in ["denoising", "reconstruction"] else "NT-Xent Loss"
        plt.ylabel(ylabel)
        
        plt.legend()
        plt.grid(True, linestyle='--', alpha=0.7)
        
        plot_path = os.path.join(self.output_dir, "ssl_loss_curve.png")
        plt.savefig(plot_path, dpi=100)
        plt.close()
        
        return "ssl_loss_curve.png"

    def on_train_end(self, trainer, pl_module):
        plot_img = self._plot_loss_curve()
        
        def get_last_valid(lst):
            valid = [x for x in lst if x is not None]
            return valid[-1] if valid else "N/A"

        final_train = get_last_valid(self.history["train_loss"])
        final_val = get_last_valid(self.history["val_loss"])

        def fmt(val):
            return f"{val:.6f}" if isinstance(val, (int, float)) else str(val)

        config_yaml = OmegaConf.to_yaml(self.cfg)
        
        # Описание метрики
        loss_desc = "MSE (Reconstruction Error)" if self.ssl_mode != "contrastive" else "Contrastive Similarity"

        md_content = f"""# 🧠 Отчет SSL ({self.ssl_mode}): {self.cfg.project_name}

**ID:** `{os.path.basename(self.output_dir)}`  
**Дата:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}  
**Модель:** `{self.cfg.model.name}`  
**Режим:** `{self.ssl_mode}`

## 1. Результаты

| Метрика | Значение (Final) | Что это значит |
| :--- | :--- | :--- |
| **Train Loss** | **{fmt(final_train)}** | {loss_desc} на обучении |
| **Val Loss** | **{fmt(final_val)}** | {loss_desc} на валидации |

## 2. Динамика обучения
![Loss Curve]({plot_img})

## 3. Полная конфигурация
<details>
<summary>🔽 Развернуть конфиг (YAML)</summary>

```yaml
{config_yaml}
</details>
Generated by SSLExperimentReporter v2
"""
        with open(self.report_path, "w", encoding="utf-8") as f:
            f.write(md_content)
            print(f"\n📝 SSL Report saved to: {self.report_path}")